stages:
  - build
  - deploy

variables:
  CONTAINER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}
  DATABASE_URI: "postgres://user:pass@postgres:5432/kalicoin_test?sslmode=disable"
  POSTGRES_DB: kalicoin_test
  POSTGRES_USER: user
  POSTGRES_PASSWORD: pass

test:
  stage: build
  image: golang:1.12
  services:
    - postgres:9.2
  script:
    - go test -mod vendor ./pkg/api
    - go test -mod vendor ./pkg/models

build:
  stage: build
  image: golang:1.12
  artifacts:
    paths:
      - kalicoin
    expire_in: 1 week
  script:
    - go build -mod vendor -o kalicoin

deploy-unstable:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  dependencies:
    - build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull "${CONTAINER_IMAGE}:unstable-${CI_COMMIT_REF_NAME}" || true
    - docker build --cache-from "${CONTAINER_IMAGE}:unstable-${CI_COMMIT_REF_NAME}" --tag "${CONTAINER_IMAGE}:unstable-${CI_COMMIT_REF_NAME}" .
    - docker push "${CONTAINER_IMAGE}:unstable-${CI_COMMIT_REF_NAME}"
  except:
    variables:
      - $CI_COMMIT_TAG =~ /^release-.*$/

deploy-stable:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  dependencies:
    - build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull "${CONTAINER_IMAGE}:latest" || true
    - docker build --cache-from "${CONTAINER_IMAGE}:latest" --tag "${CONTAINER_IMAGE}:${CI_COMMIT_TAG}" --tag "${CONTAINER_IMAGE}:latest" .
    - docker push "${CONTAINER_IMAGE}:${CI_COMMIT_TAG}"
    - docker push "${CONTAINER_IMAGE}:latest"
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^release-.*$/
