---
version: "3"

services:
  kalicoin:
    image: golang:1.12
    volumes:
      - .:/go/src/kalicoin
    working_dir: /go/src/kalicoin
    command: go run kalicoin
    environment:
      DATABASE_URI: "postgres://user:pass@postgres:5432/kalicoin?sslmode=disable"
      ENVIRONMENT: "development"
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:9.2
    environment:
      POSTGRES_DB: "kalicoin"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    ports:
      - 5432:5432

  pg_admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "kali@local.int"
      PGADMIN_DEFAULT_PASSWORD: "kalicoin"
    depends_on:
      - postgres
    ports:
      - 8080:80
